In [36]:
import numpy as np

How to create an array

In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [38]:
type(a)

numpy.ndarray

Baisc Operations of array

In [39]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [40]:
#creating a 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [41]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
print(a2.shape)
print(a3.shape) #2 2d arrays with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


In [43]:
print(a2.ndim)
print(a3.ndim)

2
3


In [44]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [45]:
#creating a 4d array
a4 = np.array([[[[1,2],[3,4]],
                [[5,6],[7,8]]],  
                [[[9,10],[11,12]],
                 [[13,14],[15,16]]]])
print(a4.shape) #2 3d arrays with 2 2d arrays with 2 rows and 2 columns

(2, 2, 2, 2)


In [46]:
print(a2.dtype)

int32


In [47]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
array=np.random.randint(1,11, size=(3,3))
print(array)

[[3 9 8]
 [8 2 2]
 [8 6 8]]


In [53]:
print(array.ndim)

2


In [55]:
x = np.array([[7,2,3],
             [2,5,2],
             [3,5,1]]) # 2d array with 3 rows and 3 columns

y = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]]) # 2d array with 3 rows and 3 columns
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(x+y)
print(x-y)
print(x*y)

[[ 8  4  6]
 [ 6 10  8]
 [10 13 10]]
[[ 6  0  0]
 [-2  0 -4]
 [-4 -3 -8]]
[[ 7  4  9]
 [ 8 25 12]
 [21 40  9]]


In [57]:
print(x@y) #matrix multiplication

[[36 48 60]
 [36 45 54]
 [30 39 48]]


In [58]:
np.dot(x,y)

array([[36, 48, 60],
       [36, 45, 54],
       [30, 39, 48]])

In [59]:
x.prod() #product of all elements in the array

12600

In [60]:
x.mean() #mean of all elements in the array

3.3333333333333335

In [61]:
y.mean()

5.0

In [62]:
x.mean(axis=0) #mean of each column

array([4., 4., 2.])

In [63]:
y.mean(axis=1) #mean of each row

array([2., 5., 8.])

In [66]:
print(x.sum()) #sum of all elements in the array
print(x.var()) #variance of all elements in the array
print(x.std()) #standard deviation of all elements in the array

30
3.3333333333333335
1.8257418583505538


In [69]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25)) #25th percentile
print(np.percentile(a, 50)) #50th percentile
print(np.percentile(a, 75)) #75th percentile

3.0
5.0
7.0


In [71]:
b = np.array([[59,29,93,93],
            [84,60,30,66],
            [66,63,38,20],
            [31,32,61,92]])
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


In [72]:
print('2x8')
print(b.reshape(2,8))

2x8
[[59 29 93 93 84 60 30 66]
 [66 63 38 20 31 32 61 92]]


In [73]:
print('8x2')
print(b.reshape(8,2))

8x2
[[59 29]
 [93 93]
 [84 60]
 [30 66]
 [66 63]
 [38 20]
 [31 32]
 [61 92]]


In [74]:
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


In [76]:
print(b[0])
print(b[1])

[59 29 93 93]
[84 60 30 66]


In [78]:
print(b[0,0])

59


In [80]:
print(b[:3])
print(b[3:])

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]]
[[31 32 61 92]]
